global:
  helmDefault: false
  defaultValueFiles:
    - values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      name: default
    source:
      repoURL: https://gitlab.com/lappis-unb/gest-odadosipea/infra-lappis-ipea.git
      targetRevision: HEAD

argocdApplications:
  superset:
    name: superset
    namespace: superset
    disableAutomated: false
    disable: false
    path: superset
    targetRevision: HEAD
    helm: false

  minio:
    name: minio
    namespace: minio
    disableAutomated: false
    disable: false
    path: minio
    targetRevision: HEAD
    helm: true

  jupyterhub:
    name: jupyterhub
    namespace: jupyterhub
    disableAutomated: false
    disable: false
    path: jupyterhub
    targetRevision: HEAD
    helm: false

  postgres:
    name: postgres
    namespace: postgresql
    disableAutomated: false
    disable: false
    path: postgres
    targetRevision: HEAD
    helm: false

  airflow:
    name: airflow
    namespace: airflow
    disableAutomated: false
    disable: false
    path: airflow
    targetRevision: HEAD
    helm: false
