global:
  helmDefault: false
  defaultValueFiles:
    - values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      name: default
    source:
      repoURL: https://github.com/GovHub-br/continuous-deployment.git
      targetRevision: HEAD

argocdApplications:
  superset:
    name: superset
    namespace: superset
    disableAutomated: false
    disable: false
    path: superset
    targetRevision: HEAD
    helm: false
    syncWave: 1

  minio:
    name: minio
    namespace: minio
    disableAutomated: false
    disable: false
    path: minio
    targetRevision: HEAD
    helm: true
    syncWave: -4

  jupyterhub:
    name: jupyterhub
    namespace: jupyterhub
    disableAutomated: false
    disable: false
    path: jupyterhub
    targetRevision: HEAD
    helm: false
    syncWave: 2

  postgres:
    name: postgres
    namespace: postgresql
    disableAutomated: false
    disable: false
    path: postgres
    targetRevision: HEAD
    helm: false
    syncWave: -5

  airflow:
    name: airflow
    namespace: airflow
    disableAutomated: false
    disable: false
    path: airflow
    targetRevision: HEAD
    helm: false
    syncWave: 0
