global:
  helmDefault: false
  valuesFile: values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      name: default
    source:
      repoURL: https://gitlab.com/lappis-unb/gest-odadosipea/infra-lappis-ipea.git
      targetRevision: HEAD

argocdApplications:
  superset:
    name: superset
    namespace: superset
    disableAutomated: false
    disable: false
    path: superset
    targetRevision: HEAD
    helm: true
  minio:
    name: minio
    namespace: minio
    disableAutomated: false
    disable: false
    path: minio
    targetRevision: HEAD
    helm: true
