minio:
  replicas: 3
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 2

  existingSecret: "minio-credentials"

  resources:
    requests:
      memory: 500Mi
      # memory: 1
  persistence:
    enabled: true
    size: 10Gi
    # size: 50
  consoleService:
    type: NodePort
    nodePort: 30006

  makePolicyJob:
    securityContext:
      enabled: true
  makeUserJob:
    securityContext:
      enabled: true
  makeServiceAccountJob:
    securityContext:
      enabled: true
  makeBucketJob:
    securityContext:
      enabled: true
  customCommandJob:
    securityContext:
      enabled: true
  postJob:
    securityContext:
      enabled: true
