apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: superset
    repo: https://apache.github.io/superset
    version: 0.12.11
    releaseName: superset
    namespace: superset
    valuesFile: ../base/values.yaml
