apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: jupyterhub
  repo: https://hub.jupyter.org/helm-chart/
  version: 3.3.7
  releaseName: jupyterhub
  namespace: jupyterhub
  valuesFile: ../base/values.yaml
  valuesInline:
    singleuser:
      storage:
        extraVolumes:
          - name: cert-volume
            secret:
              secretName: extrator-ipea-certificate
        extraVolumeMounts:
          - name: cert-volume
            mountPath: "/etc/tls/certs"
            readOnly: true

resources:
- shared-storage-pvc.yaml
