apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: jupyterhub
  repo: https://hub.jupyter.org/helm-chart/
  version: 3.3.7
  releaseName: jupyterhub
  namespace: jupyterhub
  valuesFile: ../base/values.yaml  # Certifique-se de que este caminho está correto
  valuesInline:
    singleuser:
      storage:
        capacity: 10Gi

resources:
- shared-storage-pvc.yaml
- certs-api.yaml   # Adiciona o arquivo certs-api.yaml aqui para ser processado
