apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-data
  namespace: airflow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
