apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-tmp
  namespace: airflow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
