apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-great-expectations
  namespace: airflow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
