cloudbeaver:
  replicaCount: 1
  hostNetwork: false
  image:
    repository: dbeaver/cloudbeaver
    pullPolicy: IfNotPresent
    tag: "21.3.0"

  securityContext: {}

  service:
    type: ClusterIP
    port: 8978

  storage:
    capacity: 5G

  resources:
    requests:
      cpu: 500m
      memory: "1Gi"
    limits:
      cpu: 4
      memory: "8Gi"
