superset:
  replicaCount: 2

  service:
    type: ClusterIP
    port: 8088

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  extraEnvRaw:
  - name: SUPERSET_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: superset-secret-key
        key: SUPERSET_SECRET_KEY

  envFromSecret: custom-superset-env
  secretEnv:
    create: false

  ingress:
    enabled: true
    ingressClassName: "external-nginx"
    # Extend timeout to allow long running queries.
    annotations: {
      "cert-manager.io/issuer": "superset-ui",
      "acme.cert-manager.io/http01-edit-in-place": "true",
      "nginx.ingress.kubernetes.io/proxy-connect-timeout": "300",
      "nginx.ingress.kubernetes.io/proxy-read-timeout": "300",
      "nginx.ingress.kubernetes.io/proxy-send-timeout": "300",
    }
    path: /
    pathType: ImplementationSpecific
    hosts:
      - ipea-superset.lappis.rocks
    tls:
    - secretName: ingress-superset-ui
      hosts:
        - ipea-superset.lappis.rocks

  postgresql:
    enabled: false

  redis:
    enabled: true
