apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  openmetadata-mysql-password: openmetadata_password

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-admin-credentials
type: Opaque
stringData:
  WEBSERVER_DEFAULT_USER_PASSWORD: your-pass
