apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: entrypoint
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/GovHub-br/continuous-deployment.git"
    targetRevision: HEAD
    path: argocd/entrypoints/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true
