apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-cd
  includeCRDs: false
  # TODO: substituir pelo nosso proprio repo publico de charts
  repo: https://argoproj.github.io/argo-helm
  version: 6.4.1
  releaseName: argocd
  namespace: argocd
  valuesFile: values.yaml
