notifications:
  enabled: false

controller:
  replicas: 2
  pdb:
    enabled: true
    minAvailable: 1
  metrics:
    enabled: true

server:
  replicas: 2
  metrics:
    enabled: true

  service:
    type: NodePort
    nodePortHttp: 30008
    nodePortHttps: 30009

repoServer:
  replicas: 2
  metrics:
    enabled: true
  extraContainers:
  - name: kustomized-helm
    command:
      - "/var/run/argocd/argocd-cmp-server"
    # TODO: always remember to update the image tag or automatize it
    image: quay.io/argoproj/argocd:v2.10.1
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
    volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      - mountPath: /home/argocd/cmp-server/config/plugin.yaml
        subPath: kustomized-helm.yaml
        name: argocd-cmp-cm
      # Starting with v2.4, do NOT mount the same tmp volume as the repo-server container. The filesystem separation helps
      # mitigate path traversal attacks.
      - mountPath: /tmp
        name: cmp-tmp
  volumes:
  - configMap:
      name: argocd-cmp-cm
    name: argocd-cmp-cm
  - emptyDir: {}
    name: cmp-tmp

applicationSet:
  replicas: 2
  metrics:
    enabled: true

configs:
  cmp:
    create: true
    # Kustomize build with helm
    plugins:
      kustomized-helm:
        generate:
          command: [sh, -c]
          args: [ "kustomize build --enable-helm --load-restrictor LoadRestrictionsNone" ]

  # # TODO: Argo CD RBAC policy configuration
  # ## Ref 1: https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-rbac-cm-yaml/
  # ## Ref 2: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
  # rbac:
  #   create: true
  #   # Policy rules are in the form:
  #   #  p, subject, resource, action, object, effect
  #   # Role definitions and bindings are in the form:
  #   #  g, subject, inherited-subject
  #   # policy.csv: |
  #   #   p, role:org-admin, applications, *, */*, allow
  #   #   p, role:org-admin, clusters, get, *, allow
  #   #   p, role:org-admin, repositories, *, *, allow
  #   #   p, role:org-admin, logs, get, *, allow
  #   #   p, role:org-admin, exec, create, */*, allow
  #   #   g, your-github-org:your-team, role:org-admin

  #   # -- OIDC scopes to examine during rbac enforcement (in addition to `sub` scope).
  #   # The scope value can be a string, or a list of strings.
  #   scopes: "[groups]"

  #   # -- Matcher function for Casbin, `glob` for glob matcher and `regex` for regex matcher.
  #   policy.matchMode: "glob"
