apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: airflow-web
spec:
  acme:
    email: infraestrutura.lappis@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-airflow-web
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: external-nginx
