replicaCount: 2

service:
  type: NodePort
  port: 8088
  nodePort:
    http: null

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

extraEnvRaw:
  - name: SUPERSET_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: superset-secret-key
        key: SUPERSET_SECRET_KEY
  - name: GUEST_TOKEN_JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: superset-guest-token
        key: GUEST_TOKEN_JWT_SECRET
    
configOverrides:
  feature_flags: |
    FEATURE_FLAGS = {
        "ENABLE_TEMPLATE_PROCESSING": True,
        "EMBEDDED_SUPERSET": True,
        "GUEST_TOKEN_JWT_SECRET": os.environ.get("GUEST_TOKEN_JWT_SECRET"),
    }

envFromSecret: custom-superset-env
secretEnv:
  create: false

postgresql:
  enabled: false

redis:
  enabled: true
