replicaCount: 2

service:
  type: NodePort
  port: 8088
  nodePort:
    http: null

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

extraEnvRaw:
  - name: SUPERSET_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: superset-secret-key
        key: SUPERSET_SECRET_KEY

configOverrides:
  feature_flags: |
    FEATURE_FLAGS = {
        "ENABLE_TEMPLATE_PROCESSING": True,
        "EMBEDDED_SUPERSET": True,
    }

  10-embed_guest.py: |
    ENABLE_GUEST_TOKEN = True
    GUEST_ROLE_NAME = "Admin"
    GUEST_TOKEN_JWT_ALGO = "HS256"   # segredo vem por env: GUEST_TOKEN_JWT_SECRET

    # iframe + CSP (restrinja aos domínios que vão embutir)
    ALLOW_IFRAME_EMBED = True
    TALISMAN_ENABLED = True
    TALISMAN_CONFIG = {
      "content_security_policy": {
        "frame-ancestors": ["'self'", "https://*.lappis.ipea.gov.br", "http://localhost:8000"],
      },
      "frame_options": None,
    }

envFromSecret: custom-superset-env    # mantém seu secret existente
secretEnv:
  create: false

postgresql:
  enabled: false

redis:
  enabled: true
