replicaCount: 2

service:
  type: NodePort
  port: 8088

resources:
  limits: { cpu: "1", memory: "2Gi" }
  requests: { cpu: "500m", memory: "1Gi" }

extraEnvRaw:
  - name: SUPERSET_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: superset-secret-key
        key: SUPERSET_SECRET_KEY
  - name: GUEST_TOKEN_JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: superset-guest-token
        key: GUEST_TOKEN_JWT_SECRET

configOverrides:
  "feature_flags.py": |
    FEATURE_FLAGS = {
      "EMBEDDED_SUPERSET": True,
    }

  "10-embed_guest.py": |
    ENABLE_GUEST_TOKEN = True
    GUEST_ROLE_NAME = "Embed"
    GUEST_TOKEN_JWT_ALGO = "HS256"   # segredo via env

    ALLOW_IFRAME_EMBED = True
    TALISMAN_ENABLED = True
    TALISMAN_CONFIG = {
      "content_security_policy": {
        "frame-ancestors": ["'self'", "https://*.lappis.ipea.gov.br"],
      },
      "frame_options": None,
    }

postgresql:
  enabled: false
redis:
  enabled: true
