replicaCount: 2

service:
  type: NodePort
  port: 8088
  nodePort:
    http: null

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

extraEnvRaw:
  - name: SUPERSET_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: superset-secret-key
        key: SUPERSET_SECRET_KEY

configOverrides:
  feature_flags.py: |
    FEATURE_FLAGS = {
      "ENABLE_TEMPLATE_PROCESSING": True,
      "EMBEDDED_SUPERSET": True,
    }

  00-public.py: |
    AUTH_ROLE_PUBLIC = "Public"
    PUBLIC_ROLE_LIKE = "Gamma"

  10-embed_guest.py: |
    ENABLE_GUEST_TOKEN = True
    GUEST_ROLE_NAME = "Embed"
    GUEST_TOKEN_JWT_ALGO = "HS256"

    AUTH_ROLE_PUBLIC = "Public"

    ALLOW_IFRAME_EMBED = True
    TALISMAN_ENABLED = True
    TALISMAN_CONFIG = {
      "content_security_policy": {
        "frame-ancestors": ["'self'", "https://*.lappis.ipea.gov.br", "http://localhost:8000"],
      },
      "frame_options": None,
    }

envFromSecret: custom-superset-env
secretEnv:
  create: false

postgresql:
  enabled: false

redis:
  enabled: true
