apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: superset
    repo: https://apache.github.io/superset
    version: 0.12.11
    releaseName: superset
    namespace: superset
    valuesFile: ../base/values.yaml
    valuesInline:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          acme.cert-manager.io/http01-edit-in-place: "true"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
        path: "/"
        pathType: ImplementationSpecific
        hosts:
          - "superset.lappis.ipea.gov.br"
        tls:
          - secretName: lappis-tls-certificate
            hosts:
              - "superset.lappis.ipea.gov.br"