apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: superset-ui
spec:
  acme:
    email: infraestrutura.lappis@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-superset-ui
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
