apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 15.0.0
    releaseName: postgres-release
    namespace: lappis
    valuesFile: values.yaml

resources:
- shared-storage-pvc.yaml